name: Deploy frontend (GitHub Container Registry)

on:
  push:
    branches: [kit]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          registry: ghcr.io
          context: .
          push: true
          tags: |
            rozario-frontend/${{ github.ref_name }}:${{ github.sha }}
            rozario-frontend/${{ github.ref_name }}:latest
            ghcr.io/rozario-frontend/${{ github.ref_name }}:latest
