name: Deploy frontend (ghcr.io)

on:
  push:
    branches: [kit]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set vars
        run: |
          echo "date=$(date +%d-%m-%Y.%H%M%S)" >> $GITHUB_ENV
          echo "image_name=ghcr.io/${{ github.repository }}-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.image_name }}:latest
            ${{ env.image_name }}:${{ env.date }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSHKEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ${{ env.image_name }}
            (docker stop ${{ github.event.repository.name }}-${{ github.ref_name }} && docker rm $_) || true
            docker run -dp 127.0.0.1:3006:3006 --network rozario --name ${{ github.event.repository.name }}-${{ github.ref_name }} ${{ env.image_name }}

