name: Deploy frontend (GitHub Container Registry)

on:
  push:
    branches: [kit]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current datetime
        run: echo "::set-output name=date::$(date +%d-%m-%Y.%H%M%S)"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/rozario-frontend-${{ github.ref_name }}:${{ steps.date.outputs.date }}
            ghcr.io/${{ github.actor }}/rozario-frontend-${{ github.ref_name }}:latest
